name = input('what,is your name?\n')
print = (name)
year = int(input('when is your birthday?\n'))
price = float(input('how much is it?\n'))
print(f'My name is :{name} \n I was born in {year} \n The price is {price}')